"""Browsertest van de hele app tegen een nep-Supabase. Draaien: python tests/e2e.py (vanuit de projectmap)."""
import json
import os
import subprocess
import sys
import time
from pathlib import Path

from playwright.sync_api import sync_playwright

sys.path.insert(0, os.path.dirname(__file__))
from mock_supabase import Mock  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
SHOTS = Path(os.environ.get("SHOTS", "/tmp/shots")); SHOTS.mkdir(exist_ok=True)
PORT = 8123
CONFIG = 'window.POKEDEALS={SUPABASE_URL:"http://mock.supabase.test",SUPABASE_KEY:"eyJtest",VAPID_PUBLIC_KEY:"BFWnzYpMSYNu1DKn9DONA5wou1TwuMMVLEQFfymBKkP9526Y_v15YOKl6XIYuS0o4tA2akxOUJmrlCjFo3ePynM"};'
INIT = """
Object.defineProperty(Notification, 'permission', {get: () => window.__perm || 'default', configurable: true});
Notification.requestPermission = async () => { window.__perm = 'granted'; return 'granted'; };
PushManager.prototype.getSubscription = async function () { return window.__sub || null; };
PushManager.prototype.subscribe = async function () {
  window.__sub = { endpoint: 'https://push.test/abc', toJSON: () => ({ endpoint: 'https://push.test/abc', keys: { p256dh: 'pk', auth: 'ak' } }), unsubscribe: async () => { window.__sub = null; return true; } };
  return window.__sub; };
Object.defineProperty(navigator.serviceWorker, 'ready', { get: () => Promise.resolve({ pushManager: PushManager.prototype }), configurable: true });
window.Tesseract = { recognize: async () => ({ data: { text: 'Basic\\nCharizard ex 330 HP\\nsome text\\n125/197 OBF R' } }) };
"""
fails = []


def check(cond, msg):
    print(("  ok   " if cond else "  FAIL ") + msg)
    if not cond:
        fails.append(msg)


def main():
    srv = subprocess.Popen([sys.executable, "-m", "http.server", str(PORT), "--directory", str(ROOT / "docs")], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(1)
    mock = Mock()
    for f in mock.db["forecasts"]:
        if f["product_id"] == "sv08-100":
            f["confidence"] = "laag"
    errors = []
    try:
        with sync_playwright() as pw:
            b = pw.chromium.launch(args=["--use-fake-ui-for-media-stream", "--use-fake-device-for-media-stream"])
            ctx = b.new_context(viewport={"width": 390, "height": 844}, device_scale_factor=2, permissions=["camera"], locale="nl-NL", service_workers="block")
            ctx.add_init_script(INIT)
            ctx.route("**/config.js", lambda r: r.fulfill(status=200, content_type="text/javascript", body=CONFIG))
            ctx.route("http://mock.supabase.test/**", mock.handle)
            page = ctx.new_page()
            page.on("pageerror", lambda e: errors.append(str(e)))
            page.on("console", lambda m: errors.append(m.text) if m.type == "error" and "favicon" not in m.text else None)
            base = f"http://localhost:{PORT}/"

            print("Home: alleen goedkope aanbiedingen (kansen verborgen)")
            page.goto(base)
            page.wait_for_selector(".dealsec .dealrow")
            check("Cheap listings" in page.inner_text(".dealsec"), "vak met goedkope aanbiedingen")
            check("−43%" in page.inner_text(".dealsec") and "Charizard" in page.inner_text(".dealsec") and "200.00" in page.inner_text(".dealsec"), "de uitschieter (base1-4): 200 tegen de tweede goedkoopste (350) = -43%")
            check("113.50" in page.inner_text(".dealsec").replace("\xa0", " ") or "113.5" in page.inner_text(".dealsec").replace("\xa0", " "), "winst na verzending (15), commissie en verpakking getoond: 350 x 0,94 - 0,50 - (200 + 15) = 113,50")
            check("Umbreon VMAX" not in page.inner_text(".dealsec"), "610 tegen 640 is 30 euro goedkoper, maar na pakketverzending (15) en commissie verlies: geen koopje")
            check("Blissey V" not in page.inner_text(".dealsec"), "10 tegen 13 haalt de 20%, maar de verzending (3) en kosten eten de winst op: geen koopje")
            check("next cheapest" not in page.inner_text(".dealsec"), "geen lange uitleg in de lijst")
            page.locator(".dealsec .infob").click()
            check("next cheapest" in page.inner_text("#sheet"), "uitleg achter het i'tje: vergeleken met de tweede goedkoopste")
            page.keyboard.press("Escape")
            page.goto(base + "#/home"); page.reload(); page.wait_for_selector(".dealsec .dealrow")
            deal_txt = page.inner_text(".dealsec")
            check("Pikachu ex" not in deal_txt, "geen koopje als de goedkoopste een andere uitvoering is dan de rest (Reverse Holofoil 12 tegen Normal 40/41)")
            check("Reverse Holofoil" in deal_txt and "Zzyzx" in deal_txt, "wel een koopje binnen dezelfde uitvoering, met de uitvoering als label")
            check("Blissey" not in deal_txt, "29,09 tegen 30,30 is geen koopje, ook niet met een absurde aanbieding van 9.001 in de lijst")

            check(page.locator(".homechance").count() == 0 and "Chances" not in page.inner_text(".page").split("\n"), "geen kansenlijst op Home")
            page.wait_for_function("document.querySelector('.head .sub') && document.querySelector('.head .sub').innerText.includes(':')", timeout=5000)
            check("Updated" in page.inner_text(".head .sub"), "status: " + page.inner_text(".head .sub"))
            check(":" in page.inner_text(".head .sub"), "status met tijd van de laatste update (app_status): " + page.inner_text(".head .sub"))
            page.screenshot(path=str(SHOTS / "home.png"))

            print("Home: één rij filterknopjes (soort, maximumprijs) en sorteren")
            dnames = lambda: page.locator(".dealrow .name").all_inner_texts()
            def max_price(label):
                page.get_by_role("button", name="Max price").click()
                page.get_by_role("button", name=label, exact=True).click()
            def sort_home(label):
                page.locator(".homef .sortc").click()
                page.get_by_role("button", name=label, exact=True).click()
            chip = lambda label: page.locator(".homef .fchip", has_text=label).first.click()
            check(dnames()[0] == "Zzyzx Test" and len(dnames()) == 3, f"standaard gesorteerd op winst in %: {dnames()}")
            check("3" in page.inner_text(".dealsec h3"), "teller bij de titel: " + page.inner_text(".dealsec h3"))
            max_price("Up to €25")
            check(dnames() == ["Zzyzx Test"] and "1" in page.inner_text(".dealsec h3"), f"maximumprijs € 25: {dnames()}")
            max_price("Up to €100")
            check(sorted(dnames()) == ["Surging Sparks Booster Box", "Zzyzx Test"], f"maximumprijs € 100: {dnames()}")
            max_price("Any price")
            check(len(dnames()) == 3, f"alle prijzen: alle 3: {dnames()}")
            chip("Sealed")
            check(dnames() == ["Surging Sparks Booster Box"], f"soort Sealed: {dnames()}")
            chip("Cards")
            check(sorted(dnames()) == ["Charizard", "Zzyzx Test"], f"soort Kaarten: {dnames()}")
            chip("All")
            sort_home("Highest price")
            check(dnames() == ["Charizard", "Surging Sparks Booster Box", "Zzyzx Test"], f"sorteren op hoogste prijs: {dnames()}")
            sort_home("Lowest price")
            check(dnames() == ["Zzyzx Test", "Surging Sparks Booster Box", "Charizard"], f"sorteren op laagste prijs: {dnames()}")
            sort_home("Biggest discount")
            check(dnames() == ["Zzyzx Test", "Charizard", "Surging Sparks Booster Box"], f"sorteren op grootste korting (88% / 43% / 33%): {dnames()}")
            # de keuze blijft onthouden
            max_price("Up to €100")
            page.reload(); page.wait_for_selector(".dealrow")
            check(sorted(dnames()) == ["Surging Sparks Booster Box", "Zzyzx Test"] and dnames()[0] == "Zzyzx Test", f"filter en sortering blijven onthouden na herladen: {dnames()}")
            # niets over: een knop om de filters te wissen
            chip("Sealed"); max_price("Up to €25")
            check(page.locator(".dealrow").count() == 0 and "No listings match these filters" in page.inner_text(".dealsec"), "geen resultaten: korte melding")
            page.locator(".dealsec").get_by_role("button", name="Clear filters").click()
            check(len(dnames()) == 3 and dnames()[0] == "Zzyzx Test", f"filters gewist: alles weer zichtbaar, standaardsortering: {dnames()}")

            print("Instellingen")
            page.locator("#tabs").get_by_role("link", name="Settings").click()
            page.wait_for_selector("text=Selling costs")
            check(page.url.endswith("#/settings") and page.locator("#tabs .tab.on").inner_text().strip() == "Settings", "Settings is een tab onderin: " + page.url)
            page.screenshot(path=str(SHOTS / "settings.png"), full_page=True)
            check(page.locator("text=Look ahead").count() == 0, "instellingen voor de kansen zijn verborgen")
            check(page.locator("text=Needs attention from").count() == 1, "instelling voor 'Aandacht nodig'")
            page.get_by_role("button", name="20%", exact=True).click()
            check(json.loads(page.evaluate("localStorage.getItem('pd:settings')") or "{}").get("attn_pct") == 20, "grens 'Aandacht nodig' opgeslagen")
            page.get_by_role("button", name="15%", exact=True).click()
            check(page.get_by_role("button", name="Back", exact=True).count() == 0, "Settings (een tab) heeft geen Back-knop")

            print("Detail (niet in bezit)")
            page.goto(base + "#/detail/sv03-125")
            page.wait_for_selector(".nmbox")
            check("Near Mint from" in page.inner_text(".nmbox") and "38.00" in page.inner_text(".nmbox"), "laagste NM-prijs getoond: " + page.inner_text(".nmbox").replace("\n", " "))
            check(page.locator(".chancesec").count() == 0 and "Why this chance" not in page.inner_text(".page"), "kans en uitleg verborgen op het kaartdetail")
            check("Break-even" in page.inner_text(".page"), "winstgrens blijft staan")
            check(page.locator("svg.chart").count() == 1, "grafiek aanwezig")
            page.locator("svg.chart").scroll_into_view_if_needed()
            chartbb = page.locator("svg.chart").bounding_box()
            page.mouse.move(chartbb["x"] + chartbb["width"] * 0.5, chartbb["y"] + chartbb["height"] * 0.5)
            page.mouse.down()
            page.mouse.move(chartbb["x"] + chartbb["width"] * 0.7, chartbb["y"] + chartbb["height"] * 0.5)
            check("none" not in (page.locator("svg.chart .scrubdot").get_attribute("style") or ""), "schuifbalk: prijspunt verschijnt tijdens slepen")
            check(page.locator("svg.chart text.scrubtxt").first.text_content() not in (None, ""), "schuifbalk: datum/prijs wordt getoond")
            page.mouse.up()
            page.wait_for_timeout(100)
            check("none" in (page.locator("svg.chart .scrubdot").get_attribute("style") or ""), "schuifbalk: verdwijnt weer na loslaten")
            page.screenshot(path=str(SHOTS / "detail.png"), full_page=True)

            print("Setcode-afkortingen (bijv. '30c' voor 30th Celebration)")
            page.goto(base + "#/search")
            page.get_by_placeholder("Search name, set or number").fill("charizard 30c 63")
            page.wait_for_selector(".resrow")
            check(page.locator(".resrow").count() == 1 and "30th Celebration" in page.inner_text(".resrow"),
                  "'30c' wordt herkend als 30th Celebration: " + page.inner_text(".resrow").replace("\n", " "))

            print("Zoeken: 30c dekt 30th Celebration en de 30th Classic Collection; Cardmarket-nummer BS4 is bij ons 001")
            def zoek30(term):
                page.goto(base + "#/search")
                page.wait_for_selector("input[type=search]")
                page.locator("input[type=search]").fill(term)
                page.wait_for_timeout(700)
                page.wait_for_selector(".resrow, .empty")
                return page.locator(".resrow").evaluate_all("els => els.map(e => e.innerText.replace(/\\s+/g, ' '))")
            for term in ("charizard 30c BS4", "charizard 30c bs4", "charizard 30c bs 4", "charizard 30th classic collection bs4", "charizard 30th-c BS4"):
                r = zoek30(term)
                check(r and "30th Classic Collection" in r[0] and "#001" in r[0] and not any("Base Set" in x for x in r), f"'{term}' vindt Charizard uit de 30th Classic Collection (nummer 001) bovenaan, geen lijst Charizards met nummer 4: {r}")
            r = zoek30("singles charizard bs4")
            check(len(r) == 1 and "30th Classic Collection" in r[0], f"ook via de Cardmarket-code in de link gevonden: {r}")
            r = zoek30("charizard 30c 63")
            check(len(r) == 1 and "30th Celebration" in r[0] and "#63" in r[0], f"'charizard 30c 63' vindt de kaart uit 30th Celebration: {r}")
            r = zoek30("charizard 30c")
            check(len(r) == 2 and all("30th" in x for x in r), f"'charizard 30c' toont alleen kaarten uit de 30th-sets: {r}")
            for term in ("charizard 30c bs4", "charizard (30C BS4)", "Charizard 30C BS 4"):
                r = zoek30(term)
                check(len(r) == 1 and "30th Classic Collection" in r[0] and "Cardmarket: Charizard (30C BS4)" in r[0], f"'{term}': precies de kaart met Cardmarkets eigen naam erbij: {r}")
            r = zoek30("lugia 30c ng9")
            check(len(r) == 1 and "#009" in r[0] and "Cardmarket: Lugia (30C NG9)" in r[0], f"de 'speciale' Lugia (30C NG9) wordt gevonden: {r}")
            r = zoek30("lugia 30c")
            check(len(r) == 2 and any("#77" in x for x in r) and any("#009" in x for x in r), f"'lugia 30c' toont gewone en speciale Lugia: {r}")
            for term in ("charizard 30th", "Charizard 30th"):
                r = zoek30(term)
                check(len(r) == 2 and all("30th" in x for x in r), f"'{term}': '30th' is de set (Celebration én Classic Collection), geen kaartnummer: {r}")
            r = zoek30("lugia 30th")
            check(len(r) == 2 and any("#77" in x for x in r) and any("#009" in x for x in r), f"'lugia 30th' toont gewone en vintage Lugia: {r}")
            r = zoek30("charizard 30th 63")
            check(len(r) == 1 and "#63" in r[0], f"'charizard 30th 63': set én nummer: {r}")
            for term in ("63/128", "charizard 63/128 30C", "30C 63/128"):
                r = zoek30(term)
                check(r and "30th Celebration" in r[0] and "#63" in r[0], f"'{term}': het nummer zoals onderaan de kaart: {r[:2]}")
            r = zoek30("charizard bs4")
            check(r and "Base Set" in r[0], f"zonder expliciete set blijft 'bs4' = Base Set #4: {r[:1]}")

            print("Zoeken: _____'s Pikachu en de set eerst, zoals Cardmarket het noemt (cel wp 24, obf 125)")
            for term in ("_____'s pikachu", "'s pikachu", "pikachu cel wp 24", "pikachu wp 24", "_____'s Pikachu (CEL WP 24)"):
                r = zoek30(term)
                check(r and "_____'s Pikachu" in r[0], f"'{term}' vindt _____'s Pikachu: {r[:1]}")
            r = zoek30("cel wp 24")
            check(len(r) == 1 and "_____'s Pikachu" in r[0] and "WP24" in r[0], f"'cel wp 24' (set eerst, zonder naam) vindt de kaart: {r}")
            r = zoek30("obf 125")
            check(r and "Charizard ex" in r[0] and "Obsidian Flames" in r[0], f"'obf 125' (set + nummer) vindt Charizard ex uit Obsidian Flames: {r[:1]}")
            r = zoek30("pikachu 100")
            check(r and "Pikachu ex" in r[0], f"een gewone naam + nummer werkt nog: {r[:1]}")

            print("Zoeken: kaartnamen zoals op Cardmarket")
            page.goto(base + "#/search")
            page.wait_for_selector("input[type=search]")
            def zoek(term):
                page.locator("input[type=search]").fill(term)
                page.wait_for_timeout(700)
                page.wait_for_selector(".resrow, .empty")
                return page.locator(".resrow").evaluate_all("els => els.map(e => e.innerText.replace(/\\s+/g, ' '))")
            for term in ("blissey Lv. 44 MT5", "Blissey Lv.44 (MT 5)", "blissey lv 44 mt 5", "Blissey MT5", "blissey mysterious treasures 5"):
                r = zoek(term)
                check(r and "Mysterious Treasures" in r[0] and "Blissey V" not in r[0], f"'{term}' vindt Blissey uit Mysterious Treasures als eerste: {r[:1]}")
            r = zoek("blissey")
            check(len(r) == 3, f"'blissey' toont alle drie de Blisseys: {len(r)}")
            r = zoek("blissey Lv. 44 XYZ9")
            check(len(r) >= 1 and any("Blissey" in x for x in r), f"onbekende setcode: toch Blisseys tonen i.p.v. niets: {len(r)}")
            r = zoek("zzyzx obf 7")
            check(r and "Zzyzx" in r[0], f"nummer '7' vindt kaart met nummer '007': {r[:1]}")
            r = zoek("zzyzx 007")
            check(r and "Zzyzx" in r[0], f"nummer '007' vindt kaart met nummer '007': {r[:1]}")
            r = zoek("charizard 4/102")
            check(r and "Base Set" in r[0], f"'charizard 4/102' (nummer/totaal) vindt de Base Set: {r[:1]}")

            print("Pokémon TCG Pocket-kaarten staan niet in de app")
            r = zoek("bulbasaur")
            check(r == [], f"'bulbasaur' vindt geen Pocket-kaart (Genetic Apex): {r}")
            r = zoek("bulbasaur genetic apex 001")
            check(r == [], f"ook niet op setnaam en nummer: {r}")
            r = zoek("charizard ex obsidian flames")
            check(r and "Obsidian Flames" in r[0], f"echte kaarten blijven gewoon vindbaar: {r[:1]}")

            print("Zoeken zonder login: + leidt naar login")
            page.get_by_role("link", name="Search").click() if page.locator("#tabs").is_visible() else page.goto(base + "#/search")
            page.goto(base + "#/search")
            page.get_by_placeholder("Search name, set or number").fill("charizard")
            page.wait_for_timeout(350)   # de zoekopdracht is debounced; even wachten tot de nieuwe (niet de vorige) query is verwerkt
            page.wait_for_selector(".resrow")
            check(page.locator(".resrow").count() == 4, "4 Charizard-resultaten (inclusief de 30th Celebration- en 30th Classic Collection-fixture)")
            page.screenshot(path=str(SHOTS / "search.png"))
            page.locator(".addb").first.click()
            page.wait_for_selector(".login")
            check("Log in" in page.inner_text(".login h1"), "login-scherm")
            page.locator("input[type=email]").fill("ik@example.nl")
            page.locator("input[type=password]").fill("verkeerd-wachtwoord")
            page.locator(".login .cta").click()
            page.wait_for_selector(".err:not(:empty)")
            check("Wrong email or password" in page.inner_text(".err"), "inloggen zonder account geeft melding")
            page.get_by_role("button", name="No account? Create one").click()
            page.locator("input[type=email]").fill("ik@example.nl")
            page.locator("input[type=password]").fill("kort")
            page.locator(".login .cta").click()
            check("at least 8" in page.inner_text(".err"), "te kort wachtwoord wordt geweigerd")
            page.locator("input[type=password]").fill("goed-wachtwoord-1")
            page.locator(".login .cta").click()
            page.wait_for_selector("#tabs .tab.on")
            check(mock.logged_in, "ingelogd")

            print("Toevoegen aan collectie")
            page.goto(base + "#/search")
            page.get_by_placeholder("Search name, set or number").fill("charizard ex")
            page.wait_for_selector(".resrow")
            page.locator(".addb").first.click()
            page.wait_for_selector(".addform")
            page.screenshot(path=str(SHOTS / "add.png"))
            page.locator(".addform input[aria-label='Purchase price each']").fill("30.00")
            page.locator(".addform input[aria-label='Shipping']").fill("4.00")
            page.locator(".addform input[aria-label='Cards in that order']").fill("2")
            check("€2.00 shipping counts towards" in page.inner_text(".addform").replace("\xa0", " "), "uitleg: jouw deel van de verzending (4 euro over 2 kaarten)")
            page.locator(".cta").click()
            page.wait_for_selector(".addform", state="hidden")   # het formulier sluit pas als het opslaan echt klaar is
            page.wait_for_selector(".addb.done")
            check(len(mock.db["collection"]) == 1 and mock.db["collection"][0]["purchase_price"] == 30, "rij opgeslagen met prijs 30")
            check(mock.db["collection"][0].get("purchase_shipping") == 2, f"verzending: jouw deel (2 euro) opgeslagen: {mock.db['collection'][0].get('purchase_shipping')}")
            # gegradeerd item
            page.locator(".addb").first.click()
            page.wait_for_selector(".addform")
            page.get_by_role("button", name="Graded", exact=True).click()
            page.wait_for_selector("select")
            page.locator(".addform input[aria-label='Purchase price each']").fill("120")
            page.locator(".addform select[aria-label='Language']").select_option("German")
            page.locator(".addform select[aria-label='Variant']").select_option("Reverse holo")
            page.locator(".cta").click()
            page.wait_for_selector(".addform", state="hidden")
            page.wait_for_function("document.querySelectorAll('.addb.done').length >= 1")
            check(len(mock.db["collection"]) == 2 and mock.db["collection"][1]["grade_company"] == "PSA" and mock.db["collection"][1]["grade"] == "10", "PSA 10 opgeslagen")
            check(mock.db["collection"][1].get("language") == "German" and mock.db["collection"][1].get("variant") == "Reverse holo" and mock.db["collection"][0].get("language") is None, "taal en variant opgeslagen (Engels/normaal = leeg)")

            print("Scan-flow")
            page.locator(".camb").click()
            page.wait_for_selector(".scan video")
            page.wait_for_timeout(600)
            page.locator(".shutter").click()
            page.wait_for_selector(".scanpanel .addform")
            check("Charizard ex" in page.inner_text(".scanpanel .found"), "herkend als Charizard ex: " + page.inner_text(".scanpanel .found").replace("\n", " "))
            check("Obsidian Flames" in page.inner_text(".scanpanel .found"), "juiste set via nummer 125/197")
            page.screenshot(path=str(SHOTS / "scan.png"))
            page.locator(".scanpanel .addform input[aria-label='Purchase price each']").fill("25")
            # dezelfde kaart in dezelfde staat zit al in de collectie (eerder toegevoegd voor 30): eerst een waarschuwing
            msgs = []
            page.once("dialog", lambda d: (msgs.append(d.message), d.dismiss()))
            page.locator(".scanpanel .cta").click()
            page.wait_for_timeout(600)
            check(len(msgs) == 1 and "already have 1 of" in msgs[0], f"waarschuwing bij dubbele toevoeging: {msgs}")
            check(len(mock.db["collection"]) == 2, "annuleren voegt niets toe")
            page.once("dialog", lambda d: d.accept())
            page.locator(".scanpanel .cta").click()
            page.wait_for_selector("dialog#scan:not([open])", state="attached")
            check(len(mock.db["collection"]) == 3, "gescande kaart toegevoegd na bevestigen")

            print("Scan: foto uit de galerij")
            import base64
            png = base64.b64decode("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==")
            page.locator(".camb").click()
            page.wait_for_selector(".scan video")
            check(page.locator(".scan input[type=file]:not([capture])").count() == 1, "galerij-kiezer zonder 'capture' (opent de galerij, niet de camera)")
            check("Gallery" in page.inner_text(".vf-top"), "knop 'Gallery' rechtsboven")
            page.locator(".scan input[type=file]:not([capture])").set_input_files({"name": "kaart.png", "mimeType": "image/png", "buffer": png})
            page.wait_for_selector(".scanpanel .addform")
            check("Charizard ex" in page.inner_text(".scanpanel .found"), "foto uit de galerij herkend")
            page.keyboard.press("Escape")
            page.wait_for_selector("dialog#scan:not([open])", state="attached")
            print("Scan: geen camera beschikbaar")
            page.evaluate("() => { navigator.mediaDevices.getUserMedia = () => Promise.reject(new Error('denied')); }")
            page.locator(".camb").click()
            page.wait_for_selector(".pickbtns")
            check("Take photo" in page.inner_text(".pickbtns") and "From gallery" in page.inner_text(".pickbtns"), "zonder camera: knoppen 'Take photo' en 'From gallery'")
            page.keyboard.press("Escape")
            page.wait_for_selector("dialog#scan:not([open])", state="attached")

            print("Collectie")
            for c in mock.db["collection"]:
                c["purchase_date"] = "2026-08-01"      # zodat er al een grafiek te tekenen valt
            page.goto(base + "#/collection")
            page.wait_for_selector(".rowc")
            # 2 van de 3 aankopen zijn dezelfde kaart in dezelfde (ongegradeerde) staat, en horen dus gegroepeerd te worden
            check(page.locator(".rowc").count() == 2, "2 regels (2 aankopen van dezelfde ongegradeerde kaart gegroepeerd, PSA 10 apart)")
            check("PSA 10" in page.inner_text(".list"), "PSA 10-label zichtbaar")
            check("German · Reverse holo" in page.inner_text(".list"), "taal en variant zichtbaar in de lijst")
            check("2 purchases" in page.inner_text(".list"), "gegroepeerde regel toont het aantal aankopen")
            check("Value now" in page.inner_text(".sum"), "samenvatting")
            page.wait_for_selector(".chartbox svg")
            page.screenshot(path=str(SHOTS / "collection.png"), full_page=True)
            page.get_by_role("button", name="Sort").or_(page.locator(".sortb")).first.click()
            page.get_by_role("button", name="Lowest value").click()
            vals = page.locator(".rowc .v").all_inner_texts()
            nums = [float(v.replace("€", "").replace("\u00a0", "").replace(",", "")) for v in vals]
            check(nums == sorted(nums), f"sorteren op laagste waarde: {vals}")
            print("Collectie: sorteren op A-Z, Z-A en nieuwste (laatst toegevoegd)")
            mock.db["collection"].append({"id": "px-1", "user_id": "u1", "product_id": "sv08-100", "quantity": 1, "condition": "NM", "grade_company": None, "grade": None,
                                          "purchase_price": 20, "purchase_date": "2020-01-01", "created_at": "2026-10-09T10:00:00+00:00"})   # oudste aankoop, maar als laatste toegevoegd
            page.reload(); page.wait_for_selector(".rowc")
            names = lambda: page.locator(".rowc .name").all_inner_texts()
            def sort_by(label):
                page.locator(".sortb").click()
                page.get_by_role("button", name=label).click()
            sort_by("A–Z"); n = names()
            check(n == sorted(n) and n[0].startswith("Charizard"), f"A–Z: {n}")
            sort_by("Z–A"); n = names()
            check(n == sorted(n, reverse=True) and n[0].startswith("Pikachu"), f"Z–A: {n}")
            sort_by("Newest (last added)"); n = names()
            check(n[0].startswith("Pikachu"), f"nieuwste eerst: de Pikachu is als laatste toegevoegd, ook al is de aankoopdatum de oudste: {n}")
            mock.db["collection"][-1]["created_at"] = "2020-01-02T00:00:00+00:00"       # nu is de Pikachu juist als eerste toegevoegd
            page.reload(); page.wait_for_selector(".rowc")
            n = names()
            check(n[-1].startswith("Pikachu") and n[0].startswith("Charizard"), f"nieuwste eerst, nu staat de Pikachu onderaan: {n}")
            print("Collectie: zoekbalk")
            sort_by("A–Z")
            zoek_c = lambda term: (page.locator("input[aria-label^='Search name, set']").fill(term), page.wait_for_timeout(350))
            zoek_c("pika")
            check(names() == ["Pikachu ex"] and "1 of 3 found" in page.inner_text(".fcount"), f"zoeken op naam: {names()} / " + page.inner_text(".fcount"))
            zoek_c("psa")
            check(len(names()) == 1 and "PSA 10" in page.inner_text(".list"), f"zoeken op graad (PSA): {names()}")
            zoek_c("obf")
            check(set(names()) == {"Charizard ex"} and len(names()) == 2, f"setafkorting 'obf' = Obsidian Flames: {names()}")
            zoek_c("surging sparks 100")
            check(names() == ["Pikachu ex"], f"zoeken op set en nummer: {names()}")
            zoek_c("zzzz")
            check(page.locator(".rowc").count() == 0 and "Nothing found for" in page.inner_text(".list"), "niets gevonden: uitleg getoond")
            zoek_c("")
            check(len(names()) == 3 and page.locator(".fcount").is_hidden(), f"lege zoekbalk: alles weer zichtbaar: {names()}")

            mock.db["collection"].pop(); page.reload(); page.wait_for_selector(".rowc")
            sort_by("Lowest value")

            page.get_by_role("button", name="Sealed", exact=True).click()
            check("Nothing in this selection" in page.inner_text(".list"), "filter Sealed leeg")
            page.get_by_role("button", name="All", exact=True).click()
            page.get_by_role("button", name="3M").click(); page.wait_for_selector(".chartbox svg")

            print("Detail in bezit + prijsmelding")
            page.locator(".rowc", has_text="PSA 10").click()   # de PSA 10-regel is niet gegroepeerd (1 aankoop) en navigeert dus direct naar het kaartdetail
            page.wait_for_selector(".stats")
            check("Purchase" in page.inner_text(".stats"), "aankoopblok bij bezit")
            check("Price history" in page.content() and "since purchase" not in page.content(), "grafiek toont altijd de volledige geschiedenis, geen afkapping meer bij 'sinds aankoop'")
            page.screenshot(path=str(SHOTS / "detail-owned.png"), full_page=True)
            page.locator(".tg").click()
            page.wait_for_selector(".amt input")
            check(len(mock.db["push_subscriptions"]) == 1, "push-abonnement opgeslagen")
            page.wait_for_timeout(900)
            check(len(mock.db["alerts"]) == 1 and mock.db["alerts"][0]["active"] is True, "prijsmelding opgeslagen")
            page.locator(".amt input").first.fill("20"); page.wait_for_timeout(900)
            check(mock.db["alerts"][0]["min_price"] == 20, "grens bijgewerkt")

            print("Waarde op basis van laagste aanbiedingen (i.p.v. trend)")
            col_id = next(c["id"] for c in mock.db["collection"] if c["product_id"] == "sv03-125")
            page.goto(base + f"#/detail/sv03-125?cid={col_id}")
            page.wait_for_selector(".stats")
            offs = [o for o in mock.db["offers"] if o["product_id"] == "sv03-125"]
            avg_expected = sum(o["price"] for o in offs) / len(offs)
            big_txt = page.inner_text(".big.num")
            big_val = float(big_txt.replace("€", "").replace("\xa0", "").replace(",", "").strip())
            check(abs(big_val - avg_expected) < 0.01, f"kop toont het gemiddelde van de {len(offs)} laagste aanbiedingen (verwacht {avg_expected:.2f}, gezien {big_val})")
            check("Trend price" in page.inner_text(".stats") and "45.50" in page.inner_text(".stats"), "trendprijs blijft apart zichtbaar, ter vergelijking")
            check("For sale from" in page.inner_text(".dh"), "korte uitleg bij het getoonde bedrag")

            print("Waarde met meerdere uitvoeringen en een absurde vraagprijs (Dragonite-geval)")
            page.goto(base + "#/detail/dp2-5")
            page.wait_for_selector(".offrow")
            big_txt = page.inner_text(".big.num").replace("\xa0", " ")
            check("36.46" in big_txt, f"waarde = gemiddelde van de Normal-aanbiedingen zonder de absurde (29.09 / 30.30 / 50; 9,001 > 2x mediaan valt weg) = 36.46: {big_txt}")
            check("from €29.09" in page.inner_text(".dh").replace("\xa0", " "), "de goedkoopste prijs staat er ook bij: " + page.inner_text(".dh").replace("\n", " ")[:200])
            check("Reverse Holofoil" in page.inner_text(".offrow >> nth=3") or "Reverse Holofoil" in page.inner_text(".page"), "uitvoering getoond bij de aanbieding")

            print("Lange lijst aanbiedingen: 8 tonen, rest uitklapbaar; hoofdprijs = mediaan van de 10 goedkoopste")
            page.goto(base + "#/detail/ex1-5")
            page.wait_for_selector(".offrow")
            check(page.locator(".offrow:visible").count() == 8, f"eerst 8 aanbiedingen zichtbaar: {page.locator('.offrow:visible').count()}")
            check("9.50" in page.inner_text(".big.num").replace("\xa0", " "), "hoofdprijs = mediaan van de 10 goedkoopste (5..14) = 9,50: " + page.inner_text(".big.num"))
            page.get_by_role("button", name="Show all 12 listings").click()
            check(page.locator(".offrow:visible").count() == 12, "na uitklappen alle 12")
            page.get_by_role("button", name="Show less").click()
            check(page.locator(".offrow:visible").count() == 8, "weer ingeklapt")
            page.goto(base + "#/detail/sv03-125")
            page.wait_for_selector(".offrow")
            check("Only 2 listings" in page.inner_text(".dh"), "waarschuwing bij weinig aanbod: " + page.inner_text(".dh").replace("\n", " ")[:260])

            print("Link naar Cardmarket: exacte pagina als die bekend is, anders zoeken")
            page.goto(base + "#/detail/sv03-125")
            page.wait_for_selector(".btns")
            href_exact = page.get_by_role("link", name="Open on Cardmarket", exact=True).get_attribute("href")
            check(href_exact == "https://www.cardmarket.com/en/Pokemon/Products/Singles/Obsidian-Flames/Charizard-ex-OBF125", f"exacte pagina: {href_exact}")
            page.goto(base + "#/detail/sv03-125")
            page.wait_for_selector(".nmbox")
            nm_href = page.locator("a.nmbox").get_attribute("href")
            check(nm_href == "https://www.cardmarket.com/en/Pokemon/Products/Singles/Obsidian-Flames/Charizard-ex-OBF125?minCondition=2", f"'Near Mint vanaf' is een link naar de exacte Cardmarket-pagina, gefilterd op Near Mint: {nm_href}")
            page.goto(base + "#/detail/base1-4")
            page.wait_for_selector(".btns")
            href_search = page.get_by_role("link", name="Search on Cardmarket", exact=True).get_attribute("href")
            check(href_search.startswith("https://www.cardmarket.com/en/Pokemon/Products/Search?searchString=Charizard"), f"zonder bekende pagina: zoeken: {href_search}")

            print("Watchlist: volgen vanaf kaartdetail")
            page.goto(base + "#/detail/sv08-100")
            page.wait_for_selector(".btns")
            page.get_by_role("button", name="Watch", exact=True).click()
            page.get_by_role("button", name="Watching", exact=True).wait_for()
            check(len(mock.db["watch_items"]) == 1 and mock.db["watch_items"][0]["product_id"] == "sv08-100", "kaart toegevoegd aan watchlist")
            page.get_by_role("button", name="Watching", exact=True).click()
            page.get_by_role("button", name="Watch", exact=True).wait_for()
            check(len(mock.db["watch_items"]) == 0, "kaart weer verwijderd via dezelfde knop")
            page.get_by_role("button", name="Watch", exact=True).click()
            page.get_by_role("button", name="Watching", exact=True).wait_for()
            page.goto(base + "#/detail/sv03-125")
            page.wait_for_selector(".btns")
            page.get_by_role("button", name="Watch", exact=True).click()
            page.get_by_role("button", name="Watching", exact=True).wait_for()
            check(len(mock.db["watch_items"]) == 2, "tweede kaart toegevoegd")

            print("Watchlist: tabblad, mappen, sorteren")
            page.goto(base + "#/watchlist")
            page.wait_for_selector(".wrow")
            check(page.locator(".wrow").count() == 2, "2 gevolgde kaarten zichtbaar")
            page.screenshot(path=str(SHOTS / "watchlist.png"), full_page=True)
            page.locator(".fchip.add").click()
            page.wait_for_selector(".sheetin input[type=text]")
            page.locator(".sheetin input[type=text]").fill("Interessant")
            page.get_by_role("button", name="Create folder").click()
            page.wait_for_selector(".fchip:not(.add)", state="attached")
            check(any(f["name"] == "Interessant" for f in mock.db["watch_folders"]), "map aangemaakt")
            page.locator(".morebtn").first.click()
            page.wait_for_selector(".chkrow input")
            page.locator(".chkrow input").check()
            page.wait_for_timeout(300)
            check(len(mock.db["watch_folder_items"]) == 1, "kaart aan map gekoppeld")
            page.keyboard.press("Escape")
            page.get_by_role("button", name="Interessant", exact=True).click()
            page.wait_for_selector(".wrow")
            check(page.locator(".wrow").count() == 1, "filter op map toont alleen gekoppelde kaart")
            page.get_by_role("button", name="All", exact=True).click()
            page.locator(".sortb").click()
            check(page.get_by_role("button", name="Likeliest to rise").count() == 0, "sorteren op kans is verborgen")
            page.get_by_role("button", name="Highest price").click()
            names_w = page.locator(".wrow .name").all_inner_texts()
            check(names_w == ["Charizard ex", "Pikachu ex"], "sorteren op hoogste prijs: " + str(names_w))
            check(page.locator(".wrow .bar1").count() == 0, "geen kansbalken in de watchlist")
            page.locator(".morebtn").first.click()
            page.wait_for_selector("text=Remove from watchlist")
            page.get_by_role("button", name="Remove from watchlist").click()
            page.wait_for_timeout(300)
            check(len(mock.db["watch_items"]) == 1, "verwijderd uit watchlist")

            print("Trackrecord")
            page.goto(base + "#/track")
            page.wait_for_selector(".tr-big")
            check("27 of 46" in page.inner_text(".tr-big"), "27 of 46: " + page.inner_text(".tr-big"))
            page.screenshot(path=str(SHOTS / "track.png"), full_page=True)

            print("Aankoop als bestelling (2 kaarten, verzending verdeeld naar prijs)")
            page.goto(base + "#/collection")
            page.wait_for_selector(".fab")
            n_before = len(mock.db["collection"])
            check(page.get_by_role("button", name="Add purchase").count() == 0 and page.get_by_role("button", name="Select", exact=True).count() == 0, "geen losse Aankoop/Selecteren-knoppen meer, alleen de +")
            check(page.locator(".fab").get_attribute("aria-label") == "Add", "ronde + rechtsonder met aria-label Add")
            page.locator(".fab").click()
            page.get_by_role("button", name="Add purchase").click()
            page.wait_for_selector(".orderform")
            page.locator(".orderform input[aria-label='Seller name']").fill("verkoperX")
            page.locator(".orderform input[aria-label='Shipping']").fill("4.00")
            check(page.locator(".orderform input[aria-label='Trustee fee']").count() == 1 and page.locator(".orderform input[aria-label='Purchase date']").count() == 1, "velden: naam, datum aankoop, verzendkosten, trustee fee")
            # zoeken op naam + nummer: precies de Base Set Charizard (#4), niet de andere Charizards
            page.locator(".orderform input[aria-label='Search card']").fill("charizard 4")
            page.wait_for_selector(".opickrow")
            check(page.locator(".opickrow").count() == 1 and "Base Set" in page.inner_text(".opick"), "naam + nummer vindt precies die kaart: " + page.inner_text(".opick").replace("\n", " "))
            page.locator(".orderform input[aria-label='Search card']").fill("charizard 30c 63")
            page.wait_for_function("document.querySelector('.opick') && document.querySelector('.opick').innerText.includes('30th')")
            check(page.locator(".opickrow").count() == 1, "setafkorting werkt ook in het aankoopformulier")
            for term, price, name in (("umbreon", "6.00", "Umbreon"), ("pikachu", "2.00", "Pikachu")):
                page.locator(".orderform input[aria-label='Search card']").fill(term)
                page.wait_for_function(f"document.querySelector('.opickrow') && document.querySelector('.opick').innerText.includes('{name}')")
                page.locator(".opickrow").first.click()
                page.locator(".orderform .oline input[aria-label='Price each']").last.fill(price)
            check(page.locator(".orderform .oline").count() == 2, "twee kaarten in de bestelling")
            page.get_by_role("button", name="Save purchase").click()
            page.wait_for_selector(".orderform", state="detached")
            new_rows = mock.db["collection"][n_before:]
            check(len(new_rows) == 2 and len({r["purchase_order"] for r in new_rows}) == 1 and all(r["purchase_seller"] == "verkoperX" for r in new_rows), "2 regels, zelfde bestelling en verkoper")
            check(sorted(r["purchase_shipping"] for r in new_rows) == [1, 3], f"verzending 4 euro verdeeld naar prijs 6:2 = 3 en 1: {[r['purchase_shipping'] for r in new_rows]}")

            print("Aankoop aanvullen: twee vergeten kaarten aan dezelfde aankoop toevoegen")
            n_rows = len(mock.db["collection"])
            orig = {x["id"]: (x["purchase_shipping"], x["purchase_costs"]) for x in new_rows}   # vóór het aanvullen
            page.goto(base + "#/collection")
            page.wait_for_selector(".fab")
            page.locator(".fab").click()
            page.get_by_role("button", name="Add purchase").click()
            page.wait_for_selector(".orderform")
            page.wait_for_function("document.querySelectorAll('.orderform select option').length > 1")
            opts = page.locator(".orderform select option").all_inner_texts()
            check(any("verkoperX" in o and "2 cards" in o for o in opts), f"eerdere aankoop staat in de keuzelijst: {opts}")
            page.locator(".orderform select").select_option(label=[o for o in opts if "verkoperX" in o][0])
            check(page.locator(".orderform input[aria-label='Seller name']").input_value() == "verkoperX" and page.locator(".orderform input[aria-label='Shipping']").input_value() == "4", "verkoper en verzending vooraf ingevuld")
            check("add to" in page.inner_text(".orderform h3").lower(), "kop zegt 'Add to purchase': " + page.inner_text(".orderform h3"))
            for term, price, name in (("blissey v", "2.00", "Blissey V"), ("zzyzx", "4.00", "Zzyzx")):
                page.locator(".orderform input[aria-label='Search card']").fill(term)
                page.wait_for_function(f"document.querySelector('.opickrow') && document.querySelector('.opick').innerText.includes('{name}')")
                page.locator(".opickrow").first.click()
                page.locator(".orderform .oline input[aria-label='Price each']").last.fill(price)
            page.get_by_role("button", name="Save purchase").click()
            page.wait_for_selector(".orderform", state="detached")
            order_id = new_rows[0]["purchase_order"]
            same = [r for r in mock.db["collection"] if r.get("purchase_order") == order_id]
            check(len(same) == 4 and len(mock.db["collection"]) == n_rows + 2, f"4 regels in dezelfde aankoop: {len(same)}")
            # prijzen 6, 2, 2, 4 -> verzending 4 euro opnieuw verdeeld: 1,71 / 0,57 / 0,57 / 1,15 (som 4,00)
            check(abs(sum(r["purchase_shipping"] for r in same) - 4) < 0.011, f"totale verzending blijft 4 euro: {[r['purchase_shipping'] for r in same]}")
            check(sorted(round(r["purchase_shipping"], 2) for r in same) == [0.57, 0.57, 1.15, 1.71], f"verdeeld naar prijs: {sorted(round(r['purchase_shipping'], 2) for r in same)}")
            check(all(r["purchase_seller"] == "verkoperX" for r in same), "zelfde verkoper")
            # terugzetten, zodat de vervolgtests hetzelfde uitgangspunt houden: de twee nieuwe regels weg, de oorspronkelijke verzending terug
            for r in same:
                if r["id"] in orig:
                    r["purchase_shipping"], r["purchase_costs"] = orig[r["id"]]
                else:
                    mock.db["collection"].remove(r)
            page.reload(); page.wait_for_selector(".fab")   # (zelfde adres: goto zou niet opnieuw laden)

            print("Verkopen als bestelling (dezelfde 2 kaarten aan 1 koper)")
            page.wait_for_selector(".fab")
            check(page.locator(".selbox").count() == 0 and page.locator(".selbar").is_hidden(), "zonder 'Record sale' geen vakjes en geen balk")
            page.locator(".fab").click()
            page.get_by_role("button", name="Record sale").click()
            page.wait_for_selector(".selbox")
            check(page.locator(".fab").is_hidden(), "de + verdwijnt tijdens het selecteren")
            check(page.locator(".selbar .selx").get_attribute("aria-label") == "Cancel" and "Tap the cards you sold" in page.inner_text(".selbar") and page.locator(".selbar .cta").inner_text().strip() == "Sell",
                  "balk: X (Cancel), uitleg en Sell-knop: " + page.inner_text(".selbar").replace("\n", " "))
            page.locator(".selbar .selx").click()
            check(page.locator(".selbox").count() == 0 and page.locator(".selbar").is_hidden() and page.locator(".fab").is_visible(), "X annuleert het selecteren: + weer terug")
            page.locator(".fab").click()
            page.get_by_role("button", name="Record sale").click()
            page.wait_for_selector(".selbox")
            pick_names = page.locator(".selrow .name").all_inner_texts()
            check(len(pick_names) >= 3 and pick_names == sorted(pick_names, key=str.lower), f"kaarten om aan te vinken staan op A–Z: {pick_names}")
            check(page.locator(".selbar").is_visible() and page.locator(".selbar .cta").is_enabled(), "balk onderaan; Sell kan ook zonder kaarten (voor kaarten die niet in de app staan)")
            page.locator("input[aria-label='Select Umbreon VMAX']").check()
            page.locator("input[aria-label='Select Pikachu ex']").check()
            check("2 selected" in page.inner_text(".selbar") and "(2)" in page.inner_text(".selbar .cta"), "balk telt mee: " + page.inner_text(".selbar").replace("\n", " "))
            page.screenshot(path=str(SHOTS / "selecteren.png"))
            page.locator(".selbar .cta").click()
            page.get_by_role("button", name="Save sale").wait_for()
            page.locator(".orderform input[aria-label='Buyer']").fill("kopersnaam")
            page.locator(".orderform input[aria-label='Total price']").fill("10.00")
            page.locator(".orderform input[aria-label='Shipping received']").fill("1.50")
            page.locator(".orderform input[aria-label='Shipping paid']").fill("1.20")
            check(page.locator(".orderform input[aria-label='Commission']").input_value() == "0.6", "commissie vooraf ingevuld op 6%: " + page.locator(".orderform input[aria-label='Commission']").input_value())
            # 10 + 1,50 - 1,20 - 0,60 commissie - 0,50 verpakking - kostprijs (6+3) + (2+1) = -2,80
            check("2.80" in page.inner_text(".orderform .bigline"), "winst op de verkoop: " + page.inner_text(".orderform .bigline").replace("\n", " "))
            # prijs per kaart typen: het invulveld blijft hetzelfde (toetsenbord blijft open) en het totaal loopt mee
            share = page.locator(".orderform input[aria-label='Share of price']").first
            share.click(); share.press("Control+A"); share.press_sequentially("7.25", delay=40)
            still = page.evaluate("() => document.activeElement === document.querySelector(\".orderform input[aria-label='Share of price']\")")
            other_share = page.locator(".orderform input[aria-label='Share of price']").nth(1).input_value()
            check(still, "tijdens het typen blijft het invulveld actief (toetsenbord blijft open)")
            check(abs(float(page.locator(".orderform input[aria-label='Total price']").input_value()) - (7.25 + float(other_share))) < 0.001, "totaal = som van de prijzen per kaart: " + page.locator(".orderform input[aria-label='Total price']").input_value())
            page.locator(".orderform input[aria-label='Total price']").fill("10.00")
            page.get_by_role("button", name="Save sale").click()
            page.wait_for_selector(".salecard")
            sale = mock.db["sales"][-1]
            items_s = [i for i in mock.db["sale_items"] if i["sale_id"] == sale["id"]]
            check(sale["buyer"] == "kopersnaam" and sale["total_price"] == 10 and abs(sale["commission"] - 0.6) < 1e-9, f"verkoop opgeslagen: {sale}")
            check(len(items_s) == 2 and abs(sum(i["price_share"] for i in items_s) - 10) < 1e-9 and sorted(i["cost_total"] for i in items_s) == [3, 9], f"regels: {items_s}")
            check(not any(r.get("purchase_order") == new_rows[0]["purchase_order"] for r in mock.db["collection"]), "verkochte kaarten uit 'In bezit' gehaald")
            check("kopersnaam" in page.inner_text(".salesbox") and "2.80" in page.inner_text(".salesbox"), "overzicht 'Verkocht' toont koper en winst")
            page.screenshot(path=str(SHOTS / "verkocht.png"), full_page=True)
            with page.expect_download() as dl:
                page.get_by_role("button", name="Export as CSV").click()
            csv_lines = open(dl.value.path(), encoding="utf-8-sig").read().strip().splitlines()
            check(csv_lines[0].startswith("Order number;Date;Buyer;Card;") and len(csv_lines) == 3, f"CSV: kop + 2 kaarten ({len(csv_lines)} regels)")
            import re as _re
            check(_re.fullmatch(r"pokedeals-sales-\d{4}-\d{2}-\d{2}\.csv", dl.value.suggested_filename or "") is not None, f"bestandsnaam: {dl.value.suggested_filename}")
            comm = sum(float(l.split(";")[9].replace(",", ".")) for l in csv_lines[1:])
            check(abs(comm - 0.6) < 0.011, f"commissie per kaart telt op tot 0,60: {comm}")

            print("Verkocht: zoekbalk, grafiek met kost en winst")
            mock.db["sales"] += [
                {"id": "s-anna", "user_id": "u1", "sale_date": "2026-09-01", "buyer": "Anna", "total_price": 80, "shipping_received": 0, "shipping_paid": 0, "commission": 4.8, "other_costs": 0.5, "created_at": "2026-09-01T10:00:00+00:00"},
                {"id": "s-bob", "user_id": "u1", "sale_date": "2026-08-10", "buyer": "Bob", "total_price": 30, "shipping_received": 0, "shipping_paid": 0, "commission": 1.8, "other_costs": 0.5, "created_at": "2026-08-10T10:00:00+00:00"},
            ]
            mock.db["sale_items"] += [
                {"id": "i-anna", "sale_id": "s-anna", "user_id": "u1", "product_id": "sv03-125", "quantity": 1, "condition": "NM", "grade_company": None, "grade": None, "price_share": 80, "cost_total": 50, "purchase_date": "2026-08-01"},
                {"id": "i-bob", "sale_id": "s-bob", "user_id": "u1", "product_id": "sv08-100", "quantity": 1, "condition": "NM", "grade_company": None, "grade": None, "price_share": 30, "cost_total": 40, "purchase_date": "2026-07-01"},
            ]
            page.reload(); page.wait_for_selector(".salecard")
            cards_n = lambda: page.locator(".salecard").count()
            check(cards_n() == 3 and "9.60" in page.inner_text(".salesbox .sum").replace("\xa0", " "), f"3 verkopen, winst totaal -2.80 + 24.70 - 12.30 = 9.60: " + page.inner_text(".salesbox .sum").replace("\n", " "))
            # grafiek: twee lijnen (kost en winst), legenda, en de schuifbalk toont beide waarden
            check(page.locator(".salesbox svg.chart path").count() == 2, f"grafiek met twee lijnen: {page.locator('.salesbox svg.chart path').count()}")
            check(all(w in page.inner_text(".salesbox .legend") for w in ("Paid", "Received", "Profit")), "legenda: betaald, teruggekregen en winst")
            check(page.locator(".salesbox svg.chart circle.mark").count() == 3, f"een bolletje per verkoopdag: {page.locator('.salesbox svg.chart circle.mark').count()}")
            box = page.locator(".salesbox svg.chart").bounding_box()
            page.mouse.move(box["x"] + box["width"] * 0.7, box["y"] + box["height"] * 0.5)
            page.mouse.down()
            tag = " ".join(page.locator(".salesbox svg.chart text.scrubtxt").evaluate_all("els => els.filter(e => e.style.display !== 'none').map(e => e.textContent)"))
            page.mouse.up()
            check("Paid" in tag and "Received" in tag and "Profit" in tag, f"tikken op de grafiek toont betaald, teruggekregen en winst op die datum: {tag}")
            page.screenshot(path=str(SHOTS / "verkocht_grafiek.png"), full_page=True)
            page.get_by_role("button", name="Per month").click()
            check(page.locator(".salesbox svg.chart path").count() == 2, "per maand: ook twee lijnen")
            page.get_by_role("button", name="Cumulative").click()
            # zoekbalk
            zoek_v = lambda term: (page.locator("input[aria-label^='Search buyer']").fill(term), page.wait_for_timeout(350))
            zoek_v("anna")
            check(cards_n() == 1 and "24.70" in page.inner_text(".salesbox .sum").replace("\xa0", " ") and "Profit (filtered)" in page.inner_text(".salesbox .sum"), "zoeken op koper: totaal gaat alleen over Anna: " + page.inner_text(".salesbox .sum").replace("\n", " "))
            check("1 of 3 sales" in page.inner_text(".salesbox .fcount"), "teller: " + page.inner_text(".salesbox .fcount"))
            check(page.locator(".salesbox svg.chart path").count() == 2, "de grafiek gaat mee met het filter")
            with page.expect_download() as dl_f:
                page.get_by_role("button", name="Export these sales as CSV").click()
            lines_f = open(dl_f.value.path(), encoding="utf-8-sig").read().strip().splitlines()
            check(len(lines_f) == 2 and "Anna" in lines_f[1], f"CSV bevat alleen de gefilterde verkoop: {lines_f}")
            zoek_v("pikachu")
            check(cards_n() == 2, f"zoeken op kaartnaam (Pikachu ex zit in twee verkopen): {cards_n()}")
            zoek_v("surging sparks")
            check(cards_n() == 2, f"zoeken op set: {cards_n()}")
            zoek_v("zzzz")
            check(cards_n() == 0 and "Nothing found for" in page.inner_text(".salesbox"), "niets gevonden: uitleg getoond, geen lege grafiek")
            zoek_v("")
            check(cards_n() == 3 and page.locator(".salesbox .fcount").is_hidden() and "Total profit" in page.inner_text(".salesbox .sum"), "lege zoekbalk: alles terug")
            print("Verkocht: filters (periode, uitkomst) en sorteren")
            from datetime import date as _d, timedelta as _td
            td = _d.today().isoformat()
            dates = [td, "2026-09-01", "2026-08-10"]
            buyers = lambda: page.locator(".salecard .salehead > div b").all_inner_texts()
            press = lambda label: page.get_by_role("button", name=label, exact=True).first.click()
            within = lambda n: sum(d > (_d.today() - _td(days=n)).isoformat() for d in dates)
            exp = {"1w": within(7), "1m": within(30), "3m": within(91), "1y": within(365), "2y": within(730)}
            check(buyers() == ["kopersnaam", "Anna", "Bob"], f"standaard nieuwste eerst: {buyers()}")
            for key, label in (("1w", "1W"), ("1m", "1M"), ("3m", "3M"), ("1y", "1Y"), ("2y", "2Y")):
                press(label); check(len(buyers()) == exp[key], f"periode {label}: {buyers()} (verwacht {exp[key]})")
                if exp[key]:
                    check(page.locator(".salesbox svg.chart path").count() == 2 or "too few" in page.inner_text(".salesbox .chartbox").lower(), f"grafiek bij periode {label}")
            page.get_by_role("button", name="All", exact=True).nth(0).click()   # periode terug op Alles
            press("Profit")
            check(buyers() == ["Anna"] and "24.70" in page.inner_text(".salesbox .sum").replace("\xa0", " ") and "Profit (filtered)" in page.inner_text(".salesbox .sum"), f"uitkomst Winst: {buyers()}, totaal gefilterd: " + page.inner_text(".salesbox .sum").replace("\n", " "))
            check(page.locator(".salesbox svg.chart path").count() == 2 and "1 of 3 sales" in page.inner_text(".salesbox .fcount"), "grafiek en teller gaan mee")
            press("Loss")
            check(sorted(buyers()) == ["Bob", "kopersnaam"], f"uitkomst Verlies: {buyers()}")
            page.get_by_role("button", name="All", exact=True).nth(1).click()   # uitkomst terug op Alles
            def sort_sales(label):
                page.locator(".salefilters .sortb").click()
                page.get_by_role("button", name=label).click()
            sort_sales("Biggest profit");   check(buyers() == ["Anna", "kopersnaam", "Bob"], f"sorteren grootste winst: {buyers()}")
            sort_sales("Biggest loss"); check(buyers() == ["Bob", "kopersnaam", "Anna"], f"sorteren grootste verlies: {buyers()}")
            sort_sales("Oldest first");     check(buyers() == ["Bob", "Anna", "kopersnaam"], f"sorteren oudste eerst: {buyers()}")
            press("Profit")
            page.reload(); page.wait_for_selector(".salecard")
            check(buyers() == ["Anna"], f"filters blijven onthouden na herladen: {buyers()}")
            page.locator("input[aria-label^='Search buyer']").fill("bob"); page.wait_for_timeout(350)
            check(len(buyers()) == 0 and "within these filters" in page.inner_text(".salesbox"), "zoeken + filter zonder resultaat: uitleg " + page.inner_text(".salesbox .emptyfilter").replace("\n", " "))
            page.get_by_role("button", name="Clear filters").click(); page.wait_for_selector(".salecard")
            sort_sales("Newest first")
            check(buyers() == ["kopersnaam", "Anna", "Bob"], f"filters gewist: alles weer zichtbaar: {buyers()}")

            mock.db["sales"] = [s for s in mock.db["sales"] if s["id"] not in ("s-anna", "s-bob")]
            mock.db["sale_items"] = [i for i in mock.db["sale_items"] if i["sale_id"] not in ("s-anna", "s-bob")]
            page.reload(); page.wait_for_selector(".salecard")

            print("Verkoop terugdraaien")
            page.once("dialog", lambda d: d.accept())
            page.get_by_role("button", name="Undo sale").click()
            page.wait_for_selector(".salesbox .empty")
            check(not mock.db["sales"] and len([r for r in mock.db["collection"] if r["product_id"] in ("swsh7-215", "sv08-100")]) == 2, "kaarten terug in de collectie, verkoop weg")
            page.get_by_role("button", name="Collection").click()
            page.wait_for_selector(".rowc")

            print("Gekocht en Verkocht: eigen pagina's, met aanpassen")
            page.goto(base + "#/collection"); page.wait_for_selector(".rowc")
            nav = page.inner_text(".collnav")
            check("Owned" in nav and "Bought" in nav and "Sold" in nav, f"collectie toont In bezit, Gekocht en Verkocht: {nav!r}")
            page.locator(".collnav a", has_text="Bought").click(); page.wait_for_selector(".buycard")
            check(page.url.endswith("#/gekocht") and "Total spent" in page.inner_text(".page"), "Gekocht opent een eigen pagina met alle aankopen")
            n_buys = page.locator(".buycard").count()
            n_rows = len(mock.db["collection"])
            check(n_buys >= 1, f"{n_buys} aankopen zichtbaar")
            first = page.locator(".buycard", has=page.get_by_role("button", name="Edit", exact=True)).first
            first.get_by_role("button", name="Edit", exact=True).click(); page.wait_for_selector(".orderform")
            page.locator(".orderform input[aria-label='Seller name']").fill("Testverkoper")
            page.locator(".orderform input[aria-label='Price each']").first.fill("12.34")
            page.get_by_role("button", name="Save changes").click(); page.wait_for_selector(".orderform", state="detached")
            try: page.wait_for_selector(".buylist .buycard:has-text('Testverkoper')", timeout=5000)   # de lijst wordt na het opslaan opnieuw geladen
            except Exception: pass
            fixed = [r for r in mock.db["collection"] if r.get("purchase_seller") == "Testverkoper"]
            check(fixed and any(abs(float(r["purchase_price"]) - 12.34) < 1e-9 for r in fixed), f"aankoop aangepast: verkoper en prijs opgeslagen ({len(fixed)} regels)")
            check("Testverkoper" in page.inner_text(".buylist"), "aangepaste aankoop staat meteen in de lijst")
            target = page.locator(".buycard", has_text="Testverkoper")
            target.get_by_role("button", name="Edit", exact=True).click(); page.wait_for_selector(".orderform")
            n_lines = page.locator(".orderform .oline").count()
            page.once("dialog", lambda d: d.accept())
            page.get_by_role("button", name="Delete whole purchase").click(); page.wait_for_selector(".buylist")
            page.wait_for_timeout(300)
            check(len(mock.db["collection"]) == n_rows - n_lines and not any(r.get("purchase_seller") == "Testverkoper" for r in mock.db["collection"]),
                  f"hele aankoop verwijderd ({n_lines} regels)")

            mock.db["sales"].append({"id": "s-edit", "user_id": "u1", "sale_date": "2026-10-01", "buyer": "Carla", "total_price": 50, "shipping_received": 2,
                                     "shipping_paid": 1.5, "commission": 3, "other_costs": 0.5, "created_at": "2026-10-01T10:00:00+00:00"})
            mock.db["sale_items"].append({"id": "si-edit", "sale_id": "s-edit", "user_id": "u1", "product_id": "sv08-100", "quantity": 1, "condition": "NM",
                                          "price_share": 50, "cost_total": 30, "purchase_date": "2026-09-01", "purchase_seller": "Dirk"})
            page.goto(base + "#/gekocht"); page.reload(); page.wait_for_selector(".buycard:has-text('Dirk')")
            check("sold" in page.inner_text(".buycard:has-text('Dirk')"), "verkochte kaart staat ook bij Gekocht, met de verkoper waar je hem kocht")
            page.goto(base + "#/collection"); page.wait_for_selector(".rowc")
            page.locator(".collnav a", has_text="Sold").click(); page.wait_for_selector(".salecard")
            check(page.url.endswith("#/verkocht"), "Verkocht opent een eigen pagina")
            page.locator(".salecard", has_text="Carla").get_by_role("button", name="Edit", exact=True).click(); page.wait_for_selector(".orderform")
            page.locator(".orderform input[aria-label='Buyer']").fill("Carla B")
            page.locator(".orderform input[aria-label='Total price']").fill("55")
            page.locator(".orderform input[aria-label='Cost']").first.fill("28")
            page.get_by_role("button", name="Save changes").click(); page.wait_for_selector(".salecard:has-text('Carla B')")
            sale = next(x for x in mock.db["sales"] if x["id"] == "s-edit"); item = next(x for x in mock.db["sale_items"] if x["id"] == "si-edit")
            check(sale["buyer"] == "Carla B" and float(sale["total_price"]) == 55 and float(item["price_share"]) == 55 and float(item["cost_total"]) == 28,
                  f"verkoop aangepast: {sale['buyer']}, {sale['total_price']}, deel {item['price_share']}, kost {item['cost_total']}")
            check("Carla B" in page.inner_text(".salelist"), "aangepaste verkoop staat meteen in de lijst")

            print("Advies: kopen / verkopen / verdacht")
            own = next(r for r in mock.db["collection"] if not r.get("grade_company"))
            cost = float(own["purchase_price"]) + (float(own.get("purchase_shipping") or 0) + float(own.get("purchase_costs") or 0)) / max(int(own["quantity"]), 1)
            today = "2026-10-08"
            owned_ids = {r["product_id"] for r in mock.db["collection"]}
            buy = next(pid for pid in ("base1-4", "sv03-125", "sv08-100", "swsh7-215") if pid not in owned_ids and pid != own["product_id"])
            warn = next(pid for pid in ("swsh7-215", "base1-4", "sv08-100") if pid not in (own["product_id"], buy))
            buy_name = next(p["name"] for p in mock.db["products"] if p["product_id"] == buy)
            mock.db["advice"] = [
                {"product_id": own["product_id"], "date": today, "state": "hoog", "price": round(cost * 1.6, 2), "normal": round(cost, 2), "sales7": round(cost * 1.55, 2), "sale_days": 12, "flags": [], "basis": "trend"},
                {"product_id": buy, "date": today, "state": "laag", "price": 24, "normal": 45.5, "sales7": 25, "sale_days": 10, "flags": [], "basis": "trend"},
                {"product_id": warn, "date": today, "state": "verdacht", "price": 900, "normal": 610, "sales7": 880, "sale_days": 9, "flags": ["weinig verkopers"], "basis": "trend"}]
            mock.db["advice_stats"] = [{"source": "live", "state": "laag", "n": 10, "hits": 6, "avg_ret": 0.05, "updated": today}]
            page.goto(base + "#/home"); page.reload(); page.wait_for_selector(".buysec .rowc")
            page.screenshot(path=str(SHOTS / "home_deals.png"), full_page=True)
            txt = page.inner_text(".buysec")
            check(buy_name in txt and "Deals" in txt and "Buy chance" not in txt, f"startscherm toont de deal onder 'Deals': {txt[:160]!r}")
            check(page.locator(".buysec .olk .cbar").count() == 1 and "▲ 90%" in page.inner_text(".buysec .olk"), "kansbalkje met verwachte stijging (24 → 45.50 = +90%): " + page.inner_text(".buysec .mv"))
            page.locator(".buysec .infob").click()
            check("6 of 10" in page.inner_text("#sheet"), "hoe vaak het advies klopte staat in de uitleg")
            page.keyboard.press("Escape")
            page.locator(".homef .fchip", has_text="Sealed").click()
            check("No deals match these filters" in page.inner_text(".buysec"), "filter op soort werkt ook op de deals")
            page.locator(".buysec").get_by_role("button", name="Clear filters").click()
            check(page.locator(".buysec .rowc").count() == 1, "filters wissen toont de deal weer")
            page.goto(base + "#/collection"); page.wait_for_selector(".rowc")
            check("Sell now" in page.inner_text(".page"), "collectie toont 'Sell now' voor een kaart die ruim boven normaal staat")
            page.screenshot(path=str(SHOTS / "collection_advies.png"), full_page=True)
            check(page.locator(".list .rowc .olk").count() >= 1 and "▼" in page.inner_text(".list .olk"), "collectie: balkje met verwachte daling bij die kaart")
            page.goto(base + "#/detail/" + warn); page.wait_for_selector(".advbox")
            box = page.inner_text(".advbox")
            check("Caution" in box and "no advice" in box.lower(), f"verdachte kaart: geen kopen/verkopen: {box[:120]!r}")
            page.get_by_role("button", name="Why?").click()
            check("Only 1 or 2 sellers" in page.inner_text(".advbox .facts"), "uitleg noemt de reden (weinig verkopers) in het lijstje")
            page.goto(base + "#/detail/" + buy); page.wait_for_selector(".advbox")
            check("Good buy" in page.inner_text(".advbox"), "detail van de deal toont Good buy")
            check(page.locator(".dh .olk").count() == 1, "kansbalkje naast de prijs op de kaartpagina")
            page.screenshot(path=str(SHOTS / "detail_deal.png"))
            page.locator(".advbox").get_by_role("button", name="Why?").click()
            facts = page.locator(".advbox ul.facts > li.fact").all_inner_texts()
            check(len(facts) >= 3 and page.locator(".advbox li.fact.good").count() >= 1 and any("If it recovers" in f for f in facts) and any("No signs of manipulation" in f for f in facts),
                  f"'Why?' toont een kort lijstje (li.fact) in plaats van zinnen: {facts}")
            page.screenshot(path=str(SHOTS / "why.png"), full_page=True)
            check("Usually €45.50" in page.inner_text(".page"), "stippellijn met de normale prijs (Usually) in de grafiek")
            # daling met een reden (herdruk): geen koop- of bijkoopadvies, wel de reden
            mock.db["advice"] = [{"product_id": own["product_id"], "date": today, "state": "laag", "price": round(cost * 0.6, 2), "normal": round(cost, 2), "sales7": round(cost * 0.62, 2),
                                  "sale_days": 12, "flags": [], "basis": "trend", "context": ["herdruk: in Nieuwe Set (2026-09-16)"]}]
            page.goto(base + "#/detail/" + own["product_id"] + "?c=" + own["id"]); page.wait_for_selector(".advbox")
            box = page.inner_text(".advbox")
            check("Hold" in box and "new version" in box, f"daling met een reden: Hold, met de reden erbij: {box[:140]!r}")
            page.locator(".advbox").get_by_role("button", name="Why?").click()
            check("New print just released" in page.inner_text(".advbox .facts"), "'Why?'-lijstje noemt de herdruk kort: " + page.inner_text(".advbox .facts").replace("\n", " | "))
            mock.db["advice"][0]["context"] = []
            page.reload(); page.wait_for_selector(".advbox")
            check("Buy more" in page.inner_text(".advbox"), "daling zonder reden bij een eigen kaart: Buy more")
            mock.db["advice"] = []; mock.db["advice_stats"] = []

            print("Verkoop met een kaart die niet in de app staat (Japans)")
            page.goto(base + "#/collection"); page.wait_for_selector(".fab")
            page.locator(".fab").click()
            page.get_by_role("button", name="Record sale").click()
            page.wait_for_selector(".selbar .cta")
            page.locator(".selbar .cta").click()
            page.get_by_role("button", name="Save sale").wait_for()
            page.get_by_role("button", name="+ Card that isn't in the app (e.g. Japanese)").click()
            page.locator(".orderform input[aria-label='Card name']").fill("Charizard ex sv3 066")
            page.locator(".orderform select[aria-label='Card language']").select_option("Japanese")
            page.locator(".orderform input[aria-label='Sold for']").press_sequentially("2.00", delay=30)
            still = page.evaluate("() => document.activeElement === document.querySelector(\".orderform input[aria-label='Sold for']\")")
            check(still, "typen in de prijs van de extra kaart houdt het invulveld actief")
            check(page.locator(".orderform input[aria-label='Cost you']").input_value() == "1.5", "kostprijs vooraf op 75%: " + page.locator(".orderform input[aria-label='Cost you']").input_value())
            check(page.locator(".orderform input[aria-label='Total price']").input_value() == "2", "totaal volgt de prijs: " + page.locator(".orderform input[aria-label='Total price']").input_value())
            page.locator(".orderform input[aria-label='Buyer']").fill("japankoper")
            n_coll = len(mock.db["collection"])
            page.get_by_role("button", name="Save sale").click()
            page.wait_for_selector(".salecard")
            jp = [i for i in mock.db["sale_items"] if i.get("item_name") == "Charizard ex sv3 066"]
            check(len(jp) == 1 and jp[0]["product_id"] is None and jp[0]["item_language"] == "Japanese" and jp[0]["cost_total"] == 1.5, f"regel zonder product opgeslagen: {jp}")
            check(len(mock.db["collection"]) == n_coll, "collectie ongewijzigd")
            check("Charizard ex sv3 066 (Japanese)" in page.inner_text(".salesbox"), "Japanse kaart zichtbaar bij Sold")

            print("Verwijderen")
            page.goto(base + "#/collection"); page.wait_for_selector(".rowc")
            n_coll = len(mock.db["collection"])
            page.locator(".rowc", has_text="PSA 10").click(); page.wait_for_selector(".btns")
            page.once("dialog", lambda d: d.accept())
            page.get_by_role("button", name="Remove from collection").click()
            page.wait_for_selector(".rowc")
            check(len(mock.db["collection"]) == n_coll - 1, "item verwijderd")
            b.close()
    finally:
        srv.terminate()
    real = [e for e in errors if "Failed to load resource" not in e]
    check(not real, f"geen console/pagina-fouten: {real[:3]}")
    print("\nMISLUKT:" if fails else "\nalle browsertests geslaagd", fails or "")
    sys.exit(1 if fails else 0)


if __name__ == "__main__":
    main()
